version: '3.8'

services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - PASS
        - DATABASE
        - DATA_USER
        - ROOT_PASS
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    restart: on-failure

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/eslamber/data/wordpress
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/eslamber/data/mariadb

networks:
  inception:
    driver: bridge
